# Numpy. Лабораторная работа 2

*2 балла за каждую задачу*

### Задача 1
*(2 балла)*

* Подгрузите массив с файла **iris.csv** и назовите этот массив my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [10]:
# Подгружаем массив с файла iris.csv и называем его my_array
import pandas as pd
my_array = pd.read_csv('iris.csv')

# Создаем двумерный массив из случайных чисел той же размерности, что и my_array
import numpy as np
shape = my_array.shape
my_generated_array = np.random.rand(shape[0], shape[1])


### Задача 2
*(2 балла)*

* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [12]:
# Выполняем поэлементное умножение my_array на my_generated_array
elementwise_product = my_array * my_generated_array

# Склеиваем массивы my_array, my_generated_array в один
concatenated_array = np.concatenate((my_array, my_generated_array), axis=0)

# Разделяем склеенный массив на равные части
parts = np.vsplit(concatenated_array, 3)  # Разделение на три равные части


### Задача 3
*(2 балла)*

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [14]:
subset = my_array[(my_array > 3) & (my_array < 5)]
print (subset)

     Unnamed: 0  sepal.length  sepal.width  petal.length  petal.width
0           NaN           NaN          3.5           NaN          NaN
1           NaN           4.9          NaN           NaN          NaN
2           NaN           4.7          3.2           NaN          NaN
3           NaN           4.6          3.1           NaN          NaN
4           4.0           NaN          3.6           NaN          NaN
..          ...           ...          ...           ...          ...
145         NaN           NaN          NaN           NaN          NaN
146         NaN           NaN          NaN           NaN          NaN
147         NaN           NaN          NaN           NaN          NaN
148         NaN           NaN          3.4           NaN          NaN
149         NaN           NaN          NaN           NaN          NaN

[150 rows x 5 columns]


### Задача 4
*(2 балла)*

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [16]:
three_dim_array = np.random.uniform(15, 37, size=(2, 3, 4))
print(three_dim_array)

[[[31.69180921 30.71143892 23.81137998 29.94706234]
  [21.30020499 27.50146089 34.00930654 19.46847008]
  [35.22432427 32.90350928 33.52488166 34.11878878]]

 [[15.35703803 34.35778983 21.74146455 15.01737438]
  [17.7514004  23.59371463 16.33564759 25.24835151]
  [35.75826681 32.01757549 34.896325   33.50103154]]]


### Задача 5
*(2 балла)*

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [17]:
предыдущий_массив = [10, 25, 35, 15, 30]
новый_массив = []

for значение in предыдущий_массив:
    if значение < 20:
        новый_массив.append("small")
    elif 20 <= значение <= 30:
        новый_массив.append("medium")
    else:
        новый_массив.append("large")

print(новый_массив)  # ['small', 'medium', 'large', 'small', 'medium']


['small', 'medium', 'large', 'small', 'medium']
